/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElCheckBoxGroup: typeof import('element-plus/es')['ElCheckBoxGroup']
  const ElLoading: typeof import('element-plus/es')['ElLoading']
}
